/* riscv-opcextended.h.  RISC-V extended instruction opcode.
   Copyright (C) 2021 Free Software Foundation, Inc.

   This file is part of GDB, GAS, and the GNU binutils.

   GDB, GAS, and the GNU binutils are free software; you can redistribute
   them and/or modify them under the terms of the GNU General Public
   License as published by the Free Software Foundation; either version
   3, or (at your option) any later version.

   GDB, GAS, and the GNU binutils are distributed in the hope that they
   will be useful, but WITHOUT ANY WARRANTY; without even the implied
   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
   the GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; see the file COPYING3. If not,
   see <http://www.gnu.org/licenses/>.  */

#ifndef __RISCV_OPC_THEAD__
#define __RISCV_OPC_THEAD__
/* Opcodes for T-HEAD.  */
#define MATCH_DCACHE_CALL	0x0010000b
#define MASK_DCACHE_CALL	0xffffffff
#define MATCH_DCACHE_IALL	0x0020000b
#define MASK_DCACHE_IALL	0xffffffff
#define MATCH_DCACHE_CSW	0x0210000b
#define MASK_DCACHE_CSW		0xfff07fff
#define MATCH_DCACHE_ISW	0x0220000b
#define MASK_DCACHE_ISW		0xfff07fff
#define MATCH_DCACHE_CIALL	0x0030000b
#define MASK_DCACHE_CIALL	0xffffffff
#define MATCH_DCACHE_CISW	0x0230000b
#define MASK_DCACHE_CISW	0xfff07fff
#define MATCH_DCACHE_CVAL1	0x0240000b
#define MASK_DCACHE_CVAL1	0xfff07fff
#define MATCH_DCACHE_CVA	0x0250000b
#define MASK_DCACHE_CVA		0xfff07fff
#define MATCH_DCACHE_IVA	0x0260000b
#define MASK_DCACHE_IVA		0xfff07fff
#define MATCH_DCACHE_CIVA	0x0270000b
#define MASK_DCACHE_CIVA	0xfff07fff
#define MATCH_DCACHE_CPAL1	0x0280000b
#define MASK_DCACHE_CPAL1	0xfff07fff
#define MATCH_DCACHE_CPA	0x0290000b
#define MASK_DCACHE_CPA		0xfff07fff
#define MATCH_DCACHE_IPA	0x02a0000b
#define MASK_DCACHE_IPA		0xfff07fff
#define MATCH_DCACHE_CIPA	0x02b0000b
#define MASK_DCACHE_CIPA	0xfff07fff
#define MATCH_ICACHE_IALL	0x0100000b
#define MASK_ICACHE_IALL	0xffffffff
#define MATCH_ICACHE_IALLS	0x0110000b
#define MASK_ICACHE_IALLS	0xffffffff
#define MATCH_ICACHE_IVA	0x0300000b
#define MASK_ICACHE_IVA		0xfff07fff
#define MATCH_ICACHE_IPA	0x0380000b
#define MASK_ICACHE_IPA		0xfff07fff
#define MATCH_L2CACHE_CALL	0x0150000b
#define MASK_L2CACHE_CALL	0xffffffff
#define MATCH_L2CACHE_IALL	0x0160000b
#define MASK_L2CACHE_IALL	0xffffffff
#define MATCH_L2CACHE_CIALL	0x0170000b
#define MASK_L2CACHE_CIALL	0xffffffff
#define MATCH_SYNC		0x0180000b
#define MASK_SYNC		0xffffffff
#define MATCH_SYNC_S		0x0190000b
#define MASK_SYNC_S		0xffffffff
#define MATCH_SYNC_I		0x01a0000b
#define MASK_SYNC_I		0xffffffff
#define MATCH_SYNC_IS		0x01b0000b
#define MASK_SYNC_IS		0xffffffff
#define MATCH_SFENCE_VMAS	0x0400000b
#define MASK_SFENCE_VMAS	0xfe007fff
#define MATCH_TSTNBZ		0x8000100b
#define MASK_TSTNBZ		0xfff0707f
#define MATCH_MVEQZ		0x4000100b
#define MASK_MVEQZ		0xfe00707f
#define MATCH_MVNEZ		0x4200100b
#define MASK_MVNEZ		0xfe00707f
#define MATCH_MULA		0x2000100b
#define MASK_MULA		0xfe00707f
#define MATCH_MULS		0x2200100b
#define MASK_MULS		0xfe00707f
#define MATCH_MULAW		0x2400100b
#define MASK_MULAW		0xfe00707f
#define MATCH_MULSW		0x2600100b
#define MASK_MULSW		0xfe00707f
#define MATCH_MULAH		0x2800100b
#define MASK_MULAH		0xfe00707f
#define MATCH_MULSH		0x2a00100b
#define MASK_MULSH		0xfe00707f
#define MATCH_EXT		0x0000200b
#define MASK_EXT		0x0000707f
#define MATCH_EXTU		0x0000300b
#define MASK_EXTU		0x0000707f
#define MATCH_LRB		0x0000400b
#define MASK_LRB		0xf800707f
#define MATCH_LRH		0x2000400b
#define MASK_LRH		0xf800707f
#define MATCH_LRW		0x4000400b
#define MASK_LRW		0xf800707f
#define MATCH_LRD		0x6000400b
#define MASK_LRD		0xf800707f
#define MATCH_LRBU		0x8000400b
#define MASK_LRBU		0xf800707f
#define MATCH_LRHU		0xa000400b
#define MASK_LRHU		0xf800707f
#define MATCH_LRWU		0xc000400b
#define MASK_LRWU		0xf800707f
#define MATCH_LURB		0x1000400b
#define MASK_LURB		0xf800707f
#define MATCH_LURH		0x3000400b
#define MASK_LURH		0xf800707f
#define MATCH_LURW		0x5000400b
#define MASK_LURW		0xf800707f
#define MATCH_LURD		0x7000400b
#define MASK_LURD		0xf800707f
#define MATCH_LURBU		0x9000400b
#define MASK_LURBU		0xf800707f
#define MATCH_LURHU		0xb000400b
#define MASK_LURHU		0xf800707f
#define MATCH_LURWU		0xd000400b
#define MASK_LURWU		0xf800707f
#define MATCH_REV		0x8200100b
#define MASK_REV		0xfff0707f
#define MATCH_FF0		0x8400100b
#define MASK_FF0		0xfff0707f
#define MATCH_FF1		0x8600100b
#define MASK_FF1		0xfff0707f
#define MATCH_SRB		0x0000500b
#define MASK_SRB		0xf800707f
#define MATCH_SRH		0x2000500b
#define MASK_SRH		0xf800707f
#define MATCH_SRW		0x4000500b
#define MASK_SRW		0xf800707f
#define MATCH_SRD		0x6000500b
#define MASK_SRD		0xf800707f
#define MATCH_SURB		0x1000500b
#define MASK_SURB		0xf800707f
#define MATCH_SURH		0x3000500b
#define MASK_SURH		0xf800707f
#define MATCH_SURW		0x5000500b
#define MASK_SURW		0xf800707f
#define MATCH_SURD		0x7000500b
#define MASK_SURD		0xf800707f
#define MATCH_TST		0x8800100b
#define MASK_TST		0xfc00707f
#define MATCH_SRRIW		0x1400100b
#define MASK_SRRIW		0xfe00707f
#define MATCH_SRRI		0x1000100b
#define MASK_SRRI		0xfc00707f
#define MATCH_ADDSL		0x0000100b
#define MASK_ADDSL		0xf800707f
#define MATCH_SWD		0xe000500b
#define MASK_SWD		0xf800707f
#define MATCH_SDD		0xf800500b
#define MASK_SDD		0xf800707f
#define MATCH_SDIA		0x7800500b
#define MASK_SDIA		0xf800707f
#define MATCH_SDIB		0x6800500b
#define MASK_SDIB		0xf800707f
#define MATCH_SWIA		0x5800500b
#define MASK_SWIA		0xf800707f
#define MATCH_SWIB		0x4800500b
#define MASK_SWIB		0xf800707f
#define MATCH_SHIB		0x2800500b
#define MASK_SHIB		0xf800707f
#define MATCH_SHIA		0x3800500b
#define MASK_SHIA		0xf800707f
#define MATCH_SBIA		0x1800500b
#define MASK_SBIA		0xf800707f
#define MATCH_SBIB		0x0800500b
#define MASK_SBIB		0xf800707f
#define MATCH_LWUD		0xf000400b
#define MASK_LWUD		0xf800707f
#define MATCH_LWD		0xe000400b
#define MASK_LWD		0xf800707f
#define MATCH_LDD		0xf800400b
#define MASK_LDD		0xf800707f
#define MATCH_LWUIA		0xd800400b
#define MASK_LWUIA		0xf800707f
#define MATCH_LWUIB		0xc800400b
#define MASK_LWUIB		0xf800707f
#define MATCH_LHUIA		0xb800400b
#define MASK_LHUIA		0xf800707f
#define MATCH_LHUIB		0xa800400b
#define MASK_LHUIB		0xf800707f
#define MATCH_LBUIA		0x9800400b
#define MASK_LBUIA		0xf800707f
#define MATCH_LBUIB		0x8800400b
#define MASK_LBUIB		0xf800707f
#define MATCH_LDIA		0x7800400b
#define MASK_LDIA		0xf800707f
#define MATCH_LDIB		0x6800400b
#define MASK_LDIB		0xf800707f
#define MATCH_LWIA		0x5800400b
#define MASK_LWIA		0xf800707f
#define MATCH_LWIB		0x4800400b
#define MASK_LWIB		0xf800707f
#define MATCH_LHIA		0x3800400b
#define MASK_LHIA		0xf800707f
#define MATCH_LHIB		0x2800400b
#define MASK_LHIB		0xf800707f
#define MATCH_LBIA		0x1800400b
#define MASK_LBIA		0xf800707f
#define MATCH_LBIB		0x0800400b
#define MASK_LBIB		0xf800707f
#define MATCH_REVW		0x9000100b
#define MASK_REVW		0xfff0707f
#define MATCH_FSURD		0x7000700b
#define MASK_FSURD		0xf800707f
#define MATCH_FSURW		0x5000700b
#define MASK_FSURW		0xf800707f
#define MATCH_FSRD		0x6000700b
#define MASK_FSRD		0xf800707f
#define MATCH_FSRW		0x4000700b
#define MASK_FSRW		0xf800707f
#define MATCH_FLURD		0x7000600b
#define MASK_FLURD		0xf800707f
#define MATCH_FLURW		0x5000600b
#define MASK_FLURW		0xf800707f
#define MATCH_FLRD		0x6000600b
#define MASK_FLRD		0xf800707f
#define MATCH_FLRW		0x4000600b
#define MASK_FLRW		0xf800707f
#define MATCH_IPUSH		0x0040000b
#define MASK_IPUSH		0xffffffff
#define MATCH_IPOP		0x0050000b
#define MASK_IPOP		0xffffffff
/* T-HEAD security.  */
#define MATCH_WSC		0xcff01073
#define MASK_WSC 		0xffffffff
/* T-HEAD Float for rv32.  */
#define MATCH_FMV_X_HW		0xc000100b
#define MASK_FMV_X_HW 		0xfff0707f
#define MATCH_FMV_HW_X		0xa000100b
#define MASK_FMV_HW_X 		0xfff0707f
#endif /* __RISCV_OPC_THEAD__ */
#ifdef DECLARE_INSN
DECLARE_INSN(thead_wsc, MATCH_WSC, MASK_WSC)
DECLARE_INSN(thead_dcache_giall, MATCH_DCACHE_IALL, MASK_DCACHE_IALL)
DECLARE_INSN(thead_dcache_gcall, MATCH_DCACHE_CALL, MASK_DCACHE_CALL)
DECLARE_INSN(thead_dcache_gciall, MATCH_DCACHE_CIALL, MASK_DCACHE_CIALL)
DECLARE_INSN(thead_dcache_gisw, MATCH_DCACHE_ISW, MASK_DCACHE_ISW)
DECLARE_INSN(thead_dcache_gcsw, MATCH_DCACHE_CSW, MASK_DCACHE_CSW)
DECLARE_INSN(thead_dcache_gcisw, MATCH_DCACHE_CISW, MASK_DCACHE_CISW)
DECLARE_INSN(thead_dcache_giva, MATCH_DCACHE_IVA, MASK_DCACHE_IVA)
DECLARE_INSN(thead_dcache_gcva, MATCH_DCACHE_CVA, MASK_DCACHE_CVA)
DECLARE_INSN(thead_dcache_gcval1, MATCH_DCACHE_CVAL1, MASK_DCACHE_CVAL1)
DECLARE_INSN(thead_dcache_gciva, MATCH_DCACHE_CIVA, MASK_DCACHE_CIVA)
DECLARE_INSN(thead_dcache_gipa, MATCH_DCACHE_IPA, MASK_DCACHE_IPA)
DECLARE_INSN(thead_dcache_gcpa, MATCH_DCACHE_CPA, MASK_DCACHE_CPA)
DECLARE_INSN(thead_dcache_gcpal1, MATCH_DCACHE_CPAL1, MASK_DCACHE_CPAL1)
DECLARE_INSN(thead_dcache_gcipa, MATCH_DCACHE_CIPA, MASK_DCACHE_CIPA)
DECLARE_INSN(thead_icache_giall, MATCH_ICACHE_IALL, MASK_ICACHE_IALL)
DECLARE_INSN(thead_icache_gialls, MATCH_ICACHE_IALLS, MASK_ICACHE_IALLS)
DECLARE_INSN(thead_icache_giva, MATCH_ICACHE_IVA, MASK_ICACHE_IVA)
DECLARE_INSN(thead_icache_gipa, MATCH_ICACHE_IPA, MASK_ICACHE_IPA)
DECLARE_INSN(thead_l2cache_giall, MATCH_L2CACHE_IALL, MASK_L2CACHE_IALL)
DECLARE_INSN(thead_l2cache_gcall, MATCH_L2CACHE_CALL, MASK_L2CACHE_CALL)
DECLARE_INSN(thead_l2cache_gciall, MATCH_L2CACHE_CIALL, MASK_L2CACHE_CIALL)
DECLARE_INSN(thead_sync, MATCH_SYNC, MASK_SYNC)
DECLARE_INSN(thead_sync_gi, MATCH_SYNC_I, MASK_SYNC_I)
DECLARE_INSN(thead_sync_gs, MATCH_SYNC_S, MASK_SYNC_S)
DECLARE_INSN(thead_sync_gis, MATCH_SYNC_IS, MASK_SYNC_IS)
DECLARE_INSN(thead_tstnbz, MATCH_TSTNBZ, MASK_TSTNBZ)
DECLARE_INSN(thead_mula, MATCH_MULA, MASK_MULA)
DECLARE_INSN(thead_muls, MATCH_MULS, MASK_MULS)
DECLARE_INSN(thead_mulah, MATCH_MULAH, MASK_MULAH)
DECLARE_INSN(thead_mulsh, MATCH_MULSH, MASK_MULSH)
DECLARE_INSN(thead_sfence_vmas, MATCH_SFENCE_VMAS, MASK_SFENCE_VMAS)
DECLARE_INSN(thead_mveqz, MATCH_MVEQZ, MASK_MVEQZ)
DECLARE_INSN(thead_mvnez, MATCH_MVNEZ, MASK_MVNEZ)
DECLARE_INSN(thead_mulaw, MATCH_MULAW, MASK_MULAW)
DECLARE_INSN(thead_mulsw, MATCH_MULSW, MASK_MULSW)
DECLARE_INSN(thead_ext, MATCH_EXT, MASK_EXT)
DECLARE_INSN(thead_extu, MATCH_EXTU, MASK_EXTU)
DECLARE_INSN(thead_ff1, MATCH_FF1, MASK_FF1)
DECLARE_INSN(thead_ff0, MATCH_FF0, MASK_FF1)
DECLARE_INSN(thead_rev, MATCH_REV, MASK_REV)
DECLARE_INSN(thead_lrb, MATCH_LRB, MASK_LRB)
DECLARE_INSN(thead_lrbu, MATCH_LRBU, MASK_LRBU)
DECLARE_INSN(thead_lrh, MATCH_LRH, MASK_LRH)
DECLARE_INSN(thead_lrhu, MATCH_LRHU, MASK_LRHU)
DECLARE_INSN(thead_lrw, MATCH_LRW, MASK_LRW)
DECLARE_INSN(thead_lrwu, MATCH_LRWU, MASK_LRWU)
DECLARE_INSN(thead_srb, MATCH_SRB, MASK_SRB)
DECLARE_INSN(thead_srh, MATCH_SRH, MASK_SRH)
DECLARE_INSN(thead_srw, MATCH_SRW, MASK_SRW)
DECLARE_INSN(thead_lrd, MATCH_LRD, MASK_LRD)
DECLARE_INSN(thead_srd, MATCH_SRD, MASK_SRD)
DECLARE_INSN(thead_lurb, MATCH_LURB, MASK_LURB)
DECLARE_INSN(thead_lurbu, MATCH_LURBU, MASK_LURBU)
DECLARE_INSN(thead_lurh, MATCH_LURH, MASK_LURH)
DECLARE_INSN(thead_lurhu, MATCH_LURHU, MASK_LURHU)
DECLARE_INSN(thead_lurw, MATCH_LURW, MASK_LURW)
DECLARE_INSN(thead_lurwu, MATCH_LURWU, MASK_LURWU)
DECLARE_INSN(thead_lurd, MATCH_LURD, MASK_LURD)
DECLARE_INSN(thead_surb, MATCH_SURB, MASK_SURB)
DECLARE_INSN(thead_surh, MATCH_SURH, MASK_SURH)
DECLARE_INSN(thead_surw, MATCH_SURW, MASK_SURW)
DECLARE_INSN(thead_surd, MATCH_SURD, MASK_SURD)
DECLARE_INSN(thead_tst, MATCH_TST, MASK_TST)
DECLARE_INSN(thead_srriw, MATCH_SRRIW, MASK_SRRIW)
DECLARE_INSN(thead_srri, MATCH_SRRI, MASK_SRRI)
DECLARE_INSN(thead_addsl, MATCH_ADDSL, MASK_ADDSL)
DECLARE_INSN(thead_lwd, MATCH_LWD, MASK_LWD)
DECLARE_INSN(thead_ldd, MATCH_LDD, MASK_LDD)
DECLARE_INSN(thead_swd, MATCH_SWD, MASK_SWD)
DECLARE_INSN(thead_sdd, MATCH_SDD, MASK_SDD)
DECLARE_INSN(thead_sdia, MATCH_SDIA, MASK_SDIA)
DECLARE_INSN(thead_sdib, MATCH_SDIB, MASK_SDIB)
DECLARE_INSN(thead_lwud, MATCH_LWUD, MASK_LWUD)
DECLARE_INSN(thead_swia, MATCH_SWIA, MASK_SWIA)
DECLARE_INSN(thead_swib, MATCH_SWIB, MASK_SWIB)
DECLARE_INSN(thead_shia, MATCH_SHIA, MASK_SHIA)
DECLARE_INSN(thead_shib, MATCH_SHIB, MASK_SHIB)
DECLARE_INSN(thead_sbia, MATCH_SBIA, MASK_SBIA)
DECLARE_INSN(thead_sbib, MATCH_SBIB, MASK_SBIB)
DECLARE_INSN(thead_lwuia, MATCH_LWUIA, MASK_LWUIA)
DECLARE_INSN(thead_lwuib, MATCH_LWUIB, MASK_LWUIB)
DECLARE_INSN(thead_lhuia, MATCH_LHUIA, MASK_LHUIA)
DECLARE_INSN(thead_lhuib, MATCH_LHUIB, MASK_LHUIB)
DECLARE_INSN(thead_lbuia, MATCH_LBUIA, MASK_LBUIA)
DECLARE_INSN(thead_lbuib, MATCH_LBUIB, MASK_LBUIB)
DECLARE_INSN(thead_ldia, MATCH_LDIA, MASK_LDIA)
DECLARE_INSN(thead_ldib, MATCH_LDIB, MASK_LDIB)
DECLARE_INSN(thead_lwia, MATCH_LWIA, MASK_LWIA)
DECLARE_INSN(thead_lwib, MATCH_LWIB, MASK_LWIB)
DECLARE_INSN(thead_lhia, MATCH_LHIA, MASK_LHIA)
DECLARE_INSN(thead_lhib, MATCH_LHIB, MASK_LHIB)
DECLARE_INSN(thead_lbia, MATCH_LBIA, MASK_LBIA)
DECLARE_INSN(thead_lbib, MATCH_LBIB, MASK_LBIB)
DECLARE_INSN(thead_fsurd, MATCH_FSURD, MASK_FSURD)
DECLARE_INSN(thead_revw, MATCH_REVW, MASK_REVW)
DECLARE_INSN(thead_fsurw, MATCH_FSURW, MASK_FSURW)
DECLARE_INSN(thead_flurd, MATCH_FLURD, MASK_FLURD)
DECLARE_INSN(thead_flurw, MATCH_FLURW, MASK_FLURW)
DECLARE_INSN(thead_fsrd, MATCH_FSRD, MASK_FSRD)
DECLARE_INSN(thead_fsrw, MATCH_FSRW, MASK_FSRW)
DECLARE_INSN(thead_flrd, MATCH_FLRD, MASK_FLRD)
DECLARE_INSN(thead_flrw, MATCH_FLRW, MASK_FLRW)
DECLARE_INSN(thead_ipush, MATCH_IPUSH, MASK_IPUSH)
DECLARE_INSN(thead_ipop, MATCH_IPOP, MASK_IPOP)
DECLARE_INSN(thead_fmv_x_hw, MATCH_FMV_X_HW, MASK_FMV_X_HW)
DECLARE_INSN(thead_fmv_hw_x, MATCH_FMV_HW_X, MASK_FMV_HW_X)
#endif /* DECLARE_INSN */
#ifdef DECLARE_CSR
/* T-HEAD M mode CSR.  */
#define CSR_THEAD_MXSTATUS 0x7c0
#define CSR_THEAD_MHCR 0x7c1
#define CSR_THEAD_MCOR 0x7c2
#define CSR_THEAD_MCCR2 0x7c3
#define CSR_THEAD_MCER2 0x7c4
#define CSR_THEAD_MHINT 0x7c5
#define CSR_THEAD_MRMR 0x7c6
#define CSR_THEAD_MRVBR 0x7c7
#define CSR_THEAD_MCER 0x7c8
#define CSR_THEAD_MCOUNTERWEN 0x7c9
#define CSR_THEAD_MCOUNTERINTEN 0x7ca
#define CSR_THEAD_MCOUNTEROF 0x7cb
#define CSR_THEAD_MHINT2 0x7cc
#define CSR_THEAD_MHINT3 0x7cd
#define CSR_THEAD_MRADDR 0x7e0
#define CSR_THEAD_MEXSTATUS 0x7e1
#define CSR_THEAD_MNMICAUSE 0x7e2
#define CSR_THEAD_MNMIPC 0x7e3
#define CSR_THEAD_MHPMCR 0x7f0
#define CSR_THEAD_MHPMSR 0x7f1
#define CSR_THEAD_MHPMER 0x7f2
#define CSR_THEAD_MSMPR 0x7f3
#define CSR_THEAD_MTEECFG 0x7f4
#define CSR_THEAD_MZONEID 0x7f5
#define CSR_THEAD_ML2CPID 0x7f6
#define CSR_THEAD_ML2WP 0x7f7
#define CSR_THEAD_MDTCMCR 0x7f8
#define CSR_THEAD_USP 0x7d1
#define CSR_THEAD_MCINS 0x7d2
#define CSR_THEAD_MCINDEX 0x7d3
#define CSR_THEAD_MCDATA0 0x7d4
#define CSR_THEAD_MCDATA1 0x7d5
#define CSR_THEAD_MEICR 0x7d6
#define CSR_THEAD_MEICR2 0x7d7
#define CSR_THEAD_MBEADDR 0x7d8
#define CSR_THEAD_MCPUID 0xfc0
#define CSR_THEAD_MAPBADDR 0xfc1
#define CSR_THEAD_MWMSR 0xfc2
#define CSR_THEAD_MHALTCAUSE 0xfe0
#define CSR_THEAD_MDBGINFO 0xfe1
#define CSR_THEAD_MPCFIFO 0xfe2
/* T-HEAD S mode CSR.  */
#define CSR_THEAD_SXSTATUS 0x5c0
#define CSR_THEAD_SHCR 0x5c1
#define CSR_THEAD_SCER2 0x5c2
#define CSR_THEAD_SCER 0x5c3
#define CSR_THEAD_SCOUNTERINTEN 0x5c4
#define CSR_THEAD_SCOUNTEROF 0x5c5
#define CSR_THEAD_SHINT 0x5c6
#define CSR_THEAD_SHINT2 0x5c7
#define CSR_THEAD_SHPMINHIBIT 0x5c8
#define CSR_THEAD_SHPMCR 0x5c9
#define CSR_THEAD_SHPMSR 0x5ca
#define CSR_THEAD_SHPMER 0x5cb
#define CSR_THEAD_SL2CPID 0x5cc
#define CSR_THEAD_SL2WP 0x5cd
#define CSR_THEAD_SBEADDR 0x5d0
#define CSR_THEAD_SCYCLE 0x5e0
#define CSR_THEAD_SHPMCOUNTER1 0x5e1
#define CSR_THEAD_SHPMCOUNTER2 0x5e2
#define CSR_THEAD_SHPMCOUNTER3 0x5e3
#define CSR_THEAD_SHPMCOUNTER4 0x5e4
#define CSR_THEAD_SHPMCOUNTER5 0x5e5
#define CSR_THEAD_SHPMCOUNTER6 0x5e6
#define CSR_THEAD_SHPMCOUNTER7 0x5e7
#define CSR_THEAD_SHPMCOUNTER8 0x5e8
#define CSR_THEAD_SHPMCOUNTER9 0x5e9
#define CSR_THEAD_SHPMCOUNTER10 0x5ea
#define CSR_THEAD_SHPMCOUNTER11 0x5eb
#define CSR_THEAD_SHPMCOUNTER12 0x5ec
#define CSR_THEAD_SHPMCOUNTER13 0x5ed
#define CSR_THEAD_SHPMCOUNTER14 0x5ee
#define CSR_THEAD_SHPMCOUNTER15 0x5ef
#define CSR_THEAD_SHPMCOUNTER16 0x5f0
#define CSR_THEAD_SHPMCOUNTER17 0x5f1
#define CSR_THEAD_SHPMCOUNTER18 0x5f2
#define CSR_THEAD_SHPMCOUNTER19 0x5f3
#define CSR_THEAD_SHPMCOUNTER20 0x5f4
#define CSR_THEAD_SHPMCOUNTER21 0x5f5
#define CSR_THEAD_SHPMCOUNTER22 0x5f6
#define CSR_THEAD_SHPMCOUNTER23 0x5f7
#define CSR_THEAD_SHPMCOUNTER24 0x5f8
#define CSR_THEAD_SHPMCOUNTER25 0x5f9
#define CSR_THEAD_SHPMCOUNTER26 0x5fa
#define CSR_THEAD_SHPMCOUNTER27 0x5fb
#define CSR_THEAD_SHPMCOUNTER28 0x5fc
#define CSR_THEAD_SHPMCOUNTER29 0x5fd
#define CSR_THEAD_SHPMCOUNTER30 0x5fe
#define CSR_THEAD_SHPMCOUNTER31 0x5ff
/* T-HEAD U mode CSR.  */
#define CSR_THEAD_FXCR 0x800
/* T-HEAD MMU extentions.  */
#define CSR_THEAD_SMIR 0x9c0
#define CSR_THEAD_SMEL 0x9c1
#define CSR_THEAD_SMEH 0x9c2
#define CSR_THEAD_SMCIR 0x9c3
/* T-HEAD Security CSR(May be dropped).  */
#define CSR_THEAD_MEBR 0xbe0
#define CSR_THEAD_NT_MSTATUS 0xbe1
#define CSR_THEAD_NT_MIE 0xbe2
#define CSR_THEAD_NT_MTVEC 0xbe3
#define CSR_THEAD_NT_MTVT 0xbe4
#define CSR_THEAD_NT_MEPC 0xbe5
#define CSR_THEAD_NT_MCAUSE 0xbe6
#define CSR_THEAD_NT_MIP 0xbe7
#define CSR_THEAD_NT_MINTSTATE 0xbe8
#define CSR_THEAD_NT_MXSTATUS 0xbe9
#define CSR_THEAD_NT_MEBR 0xbea
#define CSR_THEAD_NT_MSP 0xbeb
#define CSR_THEAD_T_USP 0xbec
#define CSR_THEAD_T_MDCR 0xbed
#define CSR_THEAD_T_MPCR 0xbee
#define CSR_THEAD_PMPTEECFG 0xbef
/* T-HEAD extentions.  */
DECLARE_CSR(thead_mxstatus, CSR_THEAD_MXSTATUS, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhcr, CSR_THEAD_MHCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcor, CSR_THEAD_MCOR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mccr2, CSR_THEAD_MCCR2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcer2, CSR_THEAD_MCER2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhint, CSR_THEAD_MHINT, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mrmr, CSR_THEAD_MRMR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mrvbr, CSR_THEAD_MRVBR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcer, CSR_THEAD_MCER, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcounterwen, CSR_THEAD_MCOUNTERWEN, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcounterinten, CSR_THEAD_MCOUNTERINTEN, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcounterof, CSR_THEAD_MCOUNTEROF, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhint2, CSR_THEAD_MHINT2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhint3, CSR_THEAD_MHINT3, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mraddr, CSR_THEAD_MRADDR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mexstatus, CSR_THEAD_MEXSTATUS, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mnmicause, CSR_THEAD_MNMICAUSE, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mnmipc, CSR_THEAD_MNMIPC, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhpmcr, CSR_THEAD_MHPMCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhpmsr, CSR_THEAD_MHPMSR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mhpmer, CSR_THEAD_MHPMER, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_msmpr, CSR_THEAD_MSMPR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mteecfg, CSR_THEAD_MTEECFG, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mzoneid, CSR_THEAD_MZONEID, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_ml2cpid, CSR_THEAD_ML2CPID, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_ml2wp, CSR_THEAD_ML2WP, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mdtcmcr, CSR_THEAD_MDTCMCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_usp, CSR_THEAD_USP, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcins, CSR_THEAD_MCINS, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcindex, CSR_THEAD_MCINDEX, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcdata0, CSR_THEAD_MCDATA0, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcdata1, CSR_THEAD_MCDATA1, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_meicr, CSR_THEAD_MEICR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_meicr2, CSR_THEAD_MEICR2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mbeaddr, CSR_THEAD_MBEADDR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mebr, CSR_THEAD_MEBR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mstatus, CSR_THEAD_NT_MSTATUS, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mtvec, CSR_THEAD_NT_MTVEC, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mie, CSR_THEAD_NT_MIE, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mtvt, CSR_THEAD_NT_MTVT, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mepc, CSR_THEAD_NT_MEPC, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mcause, CSR_THEAD_NT_MCAUSE, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mip, CSR_THEAD_NT_MIP, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mintstate, CSR_THEAD_NT_MINTSTATE, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mxstatus, CSR_THEAD_NT_MXSTATUS, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_mebr, CSR_THEAD_NT_MEBR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_nt_msp, CSR_THEAD_NT_MSP, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_t_usp, CSR_THEAD_T_USP, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_t_mdcr, CSR_THEAD_T_MDCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_t_mpcr, CSR_THEAD_T_MPCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_pmpteecfg, CSR_THEAD_PMPTEECFG, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mcpuid, CSR_THEAD_MCPUID, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mapbaddr, CSR_THEAD_MAPBADDR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_mwmsr, CSR_THEAD_MWMSR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_fxcr, CSR_THEAD_FXCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_smir, CSR_THEAD_SMIR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_smel, CSR_THEAD_SMEL, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_smeh, CSR_THEAD_SMEH, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_smcir, CSR_THEAD_SMCIR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_sxstatus, CSR_THEAD_SXSTATUS, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shcr, CSR_THEAD_SHCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_scer2, CSR_THEAD_SCER2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_scer, CSR_THEAD_SCER, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_scounterinten , CSR_THEAD_SCOUNTERINTEN, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_scounterof, CSR_THEAD_SCOUNTEROF, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shint, CSR_THEAD_SHINT, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shint2, CSR_THEAD_SHINT2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpminhibit, CSR_THEAD_SHPMINHIBIT, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcr, CSR_THEAD_SHPMCR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmsr, CSR_THEAD_SHPMSR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmer, CSR_THEAD_SHPMER, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_sl2cpid, CSR_THEAD_SL2CPID, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_sl2wp, CSR_THEAD_SL2WP, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_sbeaddr, CSR_THEAD_SBEADDR, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_scycle, CSR_THEAD_SCYCLE, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter1, CSR_THEAD_SHPMCOUNTER1, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter2, CSR_THEAD_SHPMCOUNTER2, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter3, CSR_THEAD_SHPMCOUNTER3, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter4, CSR_THEAD_SHPMCOUNTER4, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter5, CSR_THEAD_SHPMCOUNTER5, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter6, CSR_THEAD_SHPMCOUNTER6, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter7, CSR_THEAD_SHPMCOUNTER7, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter8, CSR_THEAD_SHPMCOUNTER8, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter9, CSR_THEAD_SHPMCOUNTER9, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter10, CSR_THEAD_SHPMCOUNTER10, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter11, CSR_THEAD_SHPMCOUNTER11, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter12, CSR_THEAD_SHPMCOUNTER12, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter13, CSR_THEAD_SHPMCOUNTER13, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter14, CSR_THEAD_SHPMCOUNTER14, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter15, CSR_THEAD_SHPMCOUNTER15, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter16, CSR_THEAD_SHPMCOUNTER16, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter17, CSR_THEAD_SHPMCOUNTER17, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter18, CSR_THEAD_SHPMCOUNTER18, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter19, CSR_THEAD_SHPMCOUNTER19, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter20, CSR_THEAD_SHPMCOUNTER20, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter21, CSR_THEAD_SHPMCOUNTER21, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter22, CSR_THEAD_SHPMCOUNTER22, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter23, CSR_THEAD_SHPMCOUNTER23, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter24, CSR_THEAD_SHPMCOUNTER24, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter25, CSR_THEAD_SHPMCOUNTER25, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter26, CSR_THEAD_SHPMCOUNTER26, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter27, CSR_THEAD_SHPMCOUNTER27, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter28, CSR_THEAD_SHPMCOUNTER28, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter29, CSR_THEAD_SHPMCOUNTER29, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter30, CSR_THEAD_SHPMCOUNTER30, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
DECLARE_CSR(thead_shpmcounter31, CSR_THEAD_SHPMCOUNTER31, CSR_CLASS_THEAD, PRIV_SPEC_CLASS_NONE, PRIV_SPEC_CLASS_NONE)
#endif /* DECLARE_CSR */
